### ISSUE TITLE
Succeeds with missing input file

### ISSUE THREAD

**Issue by mih** [m-wierzba/cat-container#3]
This is more of a general CAT issue, but reporting it nevertheless:

```
mih@cpu4 ~ % singularity run --cleanenv cat.simg -b /batch/cat_standalone_segment.txt
singularity run --cleanenv cat.simg -b /batch/cat_standalone_segment.txt  18.69s user 3.62s system 84% cpu 26.364 total
mih@cpu4 ~ % echo $?
0
```

I would have expected an error, but got none.

**Comment by m-wierzba** [comment]
I think solving #6, solves this one as well. The error message comes from CAT though.

Let me know, if this is sufficient.
