### ISSUE TITLE
No error message on inappropriate input 

### ISSUE THREAD

**Issue by mih** [m-wierzba/cat-container#4]
This is related to #3, but not the same issue:

```
mih@cpu4 ~ % singularity run --cleanenv cat.simg -b /batch/cat_standalone_segment.txt sub-02_T1w.json
```

This error with exit code 1 (sensible), but gives no error message at all. In this case the reason is somewhat obvious, but it could also have been a broken nifti file.

**Comment by m-wierzba** [comment]
I think solving #6, solves this one as well. The error message comes from CAT though.

Let me know, if this is sufficient.
