### ISSUE TITLE
No output when running

### ISSUE THREAD

**Issue by mih** [m-wierzba/cat-container#6]
```
mih@cpu4 ~ % singularity run --cleanenv cat.simg -b /batch/cat_standalone_segment.txt test_t1w.nii.gz
```

It is like this for 15min. Searching around, I found a CAT log file that is being updated nicely, and tell me that it is all good. But maybe that should go to stdout/err instead?

**Comment by m-wierzba** [comment]
Added, 4f2716611c1ef0448404e69ff163a5ff9b692df4.

Using `tee`, as suggested. :)
